[package]
name = "tauri-plugin-awesome"
version = "0.0.0"
authors = [ "You" ]
description = ""
edition = "2021"
rust-version = "1.59"
exclude = ["/examples"]

[dependencies]
tauri = { version = "1.2.1" }
